### ISSUE TITLE
Option to disable PostgresConnection

### ISSUE THREAD

**Issue by fsou** [umbrellio/laravel-pg-extensions#39]
At our team, we are trying to use  [umbrellio/laravel-ltree](https://github.com/umbrellio/laravel-ltree) on a laravel project.

Currently all tests are using an on memory sqlite database connection.

From the moment we added laravel-ltree extension, all tests started to fail as every connection started to be made using class [Umbrellio\Postgres\PostgresConnection](https://github.com/umbrellio/laravel-pg-extensions/blob/master/src/PostgresConnection.php).

Is there any way I can chose when to use this class or not to handle my database connections?

Thank you,
Filipe

**Comment by pvsaintpe** [comment]
@fsou 

ltree is an extension of the postgres database, and implies the use of materialized paths to quickly find the desired node or branch of trees. Using other databases seems to me not entirely correct.

In your db (SQLite) do you store the tree in a flat form (id, parent_id, path???)? If it has an infinite level of nesting, how can you work in sqlite with the maintenance of such a tree, so that having 1 SQL query, how you can get tree from leaves to the root by any of its nodes?

**Comment by pvsaintpe** [comment]
By the way, why can't you use different database connections in your tests, or PostgresConnection for this test?

**Comment by fsou** [comment]
Hi @pvsaintpe, thank you for your quick reply.

We are trying to accommodate the extension in our Laravel project, that already have above 1800 tests, currently using SQLite as testing database.

From the moment we add laravel-ltree to our composer dependencies, all the database connections try to use PostgresConnection.

Currently we don't store any kind of tree, that's what we are trying to achieve with Umbrellio extension.

For any test using ltree I would definitely need a Postgres Database, but for all the test we currently have, we won't need it, so here's the need for us to have such an option.

Hope this could give you an overview of our problem right now.

Thank you for your support.
Filipe

**Comment by pvsaintpe** [comment]
@fsou 

Try using build version 4.5.0, I added options so you can use other connections in tests with

**Comment by fsou** [comment]
> @fsou
> 
> Try using build version 4.5.0, I added options so you can use other connections in tests with

@pvsaintpe Works perfectly!

Thank you!

**Comment by pvsaintpe** [comment]
@fsou 

If there are additional suggestions or suggestions for finalising the package, I would appreciate active feedback.
