### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by jamesRUS52** [umbrellio/laravel-pg-extensions#59]
Is any plans to implement array types ?

**Comment by pvsaintpe** [comment]
Hi, @jamesRUS52 

Yes, tell me exactly what you need, we'll add it.

**Comment by jamesRUS52** [comment]
It would by nice If you will implement the next data types for migration procedure
integer[]
charaster varying[]
real[]
real
interval

and one more question
Is it possible to work with this types in models? or use in casting like 
$cast = [
  'column1' => 'interval',
  'column2' => 'stringArray'
]

It simple to make cast class for integer array or real array, interval not too hard too (I did that), but it is not trivial for string array
postgres returns string depend on content (is space in string or not, double quote or single quote etc )

**Comment by pvsaintpe** [comment]
@jamesRUS52 

That's interesting. Okay. Let me analyze and answer in a week.

I don't think it's difficult there.
