### ISSUE TITLE
Добавить поддержку int4range

### ISSUE THREAD

**Issue by kvatra** [umbrellio/laravel-pg-extensions#63]
Было бы круто по аналогии с tsrange добавить возможность создавать колонку int4range

**Comment by pvsaintpe** [comment]
Там вообще много range типов, тебе только один нужен?

**Comment by kvatra** [comment]
Все - хорошо, но мне пока да, нужен инт4 и ts.

Было бы круто ещё каст типов на елоквенте сделать на них.

**Comment by belamov** [comment]
@kvatra 
https://github.com/belamov/postgres-range
вот пакет, который добавляет поддержку этих типов в ларавел
можно установить параллельно, я думаю
