### ISSUE TITLE
Cannot resolve PostgresConnection in Laravel11.x

### ISSUE THREAD

**Issue by fuwasegu** [umbrellio/laravel-pg-extensions#89]
As per pull request [#48864](https://github.com/laravel/framework/pull/48864) in Laravel, Laravel has abandoned its dependency on DBAL (Database Abstraction Layer) during the migration to 11.x.
In the process, methods related to Doctrine that were implemented in Illuminate\Database\Connection::class have also been removed.
Although this library was recently updated to support Laravel 11.x and its major version was bumped to 6, it still seems to be using methods like DB::registerDoctrineType(), which suggests that it has not actually followed the changes made in Laravel 11.x.

The issue is that non-existent methods continue to be called from the DB Facade, causing the resolution of the Connection to recurse infinitely, which leads to the processing getting stuck.

Thanks．

**Comment by pvsaintpe** [comment]
Fixed in version 7.0.1

**Comment by mpyw** [comment]
This looks to be not sufficient, actually fixed in forked [fuwasegu/laravel-pg-extensions-next](https://github.com/fuwasegu/laravel-pg-extensions-next?tab=readme-ov-file)

**Comment by pvsaintpe** [comment]
@mpyw 

Please, send pull request into mi repo with the fix. Thank you.
